#!/usr/bin/bash

set -e
set -x

base_dir="$(pwd)"
work_dir="$base_dir"/work
cache_dir="$work_dir"/cache
os_dir="$work_dir"/os
repo_dir="$base_dir"/out/repo
conf_dir="$base_dir"/conf
out_dir="$base_dir"/out
conf_dir="$base_dir"/conf
ostree_dir="$out_dir"/ostree

die() {
    echo "$@"
    exit 1
}

(( EUID != 0 )) && die "This script must be run as root."

. "$conf_dir"/eta.conf

cp -f "$conf_dir"/pacman.conf "$work_dir"

sed -i "s:^#CacheDir.*:CacheDir = $cache_dir:" "$work_dir"/pacman.conf

echo -e "\n[$OSNAME]\nSigLevel = Never\nServer = file://$repo_dir" >> \
    "$work_dir"/pacman.conf

for module in $MODULES:
do
    rm -f "$cache_dir"/$module-*
done

rm -rf "$os_dir"
mkdir -p "$os_dir"

pacstrap -dcC "$work_dir"/pacman.conf "$os_dir" $PKGS

kernel_version=$(pacman -r "$os_dir" -Q linux | cut -d' ' -f 2)-ARCH

systemd-nspawn -D "$os_dir" \
    mkinitcpio -c /etc/ostree-mkinitcpio.conf -g /boot/initramfs-linux.img \
        -k $kernel_version

mkdir -p "$os_dir"/sysroot

boot_dir="$os_dir"/boot

rm -f "$boot_dir"/initramfs-linux-fallback.img

checksum=$(cat "$boot_dir"/initramfs-* "$boot_dir"/vmlinuz-* | \
           sha256sum | cut -d' ' -f 1)

mv "$boot_dir"/initramfs-*.img "$boot_dir"/initramfs-$checksum
mv "$boot_dir"/vmlinuz-* "$boot_dir"/vmlinuz-$checksum

if [ ! -d "$ostree_dir" ]; then
    ostree --repo="$ostree_dir" init --mode archive-z2
fi

ostree --repo="$ostree_dir" commit --tree=dir="$os_dir" --branch=master \
    --subject "Update"
