#!/usr/bin/bash

set -e
set -x

base_dir="$(pwd)"
out_dir="$base_dir"/out
work_dir="$base_dir"/work
conf_dir="$base_dir"/conf

die() {
    echo "$@"
    exit 1
}

. "$conf_dir"/eta.conf

(( EUID != 0 )) && die "This script must be run as root."

find "$work_dir" -mindepth 1 -maxdepth 1 ! -name cache -exec rm -rf {} \;
find "$out_dir" -mindepth 1 -maxdepth 1 ! -name ostree -exec rm -rf {} \;

for module in $MODULES
do
    sudo -u $SUDO_USER bash -c "cd source/$module; git clean -fdx"
done
