#!/usr/bin/bash

set -e
set -x

base_dir="$(pwd)"
out_dir="$base_dir"/out
conf_dir="$base_dir"/conf
ostree_dir="$out_dir"/ostree

. "$conf_dir"/eta.conf

image_path="$out_dir"/$OSNAME.img

rm -f "$image_path"

sudo -u $SUDO_USER truncate -s 5GB "$image_path"

parted "$image_path" mklabel msdos
parted "$image_path" mkpart primary ext4 0% 10%
parted "$image_path" mkpart primary ext4 10% 100%
parted "$image_path" set 1 boot on

modprobe loop

losetup /dev/loop0 "$image_path" -o 1048576 --sizelimit 499121664
losetup /dev/loop1 "$image_path" -o 500170752 --sizelimit 4499439104

sysroot=/mnt

mkfs.ext4 /dev/loop0
mkfs.ext4 /dev/loop1

e2label /dev/loop1 $OSNAME

mount /dev/loop1 "$sysroot"
mkdir -p "$sysroot"/boot
mount /dev/loop0 "$sysroot"/boot

mkdir "$sysroot"/boot/loader.0
touch "$sysroot"/boot/loader.0/syslinux.cfg
ln -s loader.0 "$sysroot"/boot/loader

mkdir "$sysroot"/boot/syslinux
ln -s ../loader/syslinux.cfg "$sysroot"/boot/syslinux/syslinux.cfg

ostree admin --sysroot="$sysroot" os-init $OSNAME

ostree --repo="$sysroot"/ostree/repo pull-local "$ostree_dir" master

ostree admin --sysroot="$sysroot" \
    deploy master --karg=root=LABEL=$OSNAME --os=$OSNAME

extlinux -i "$sysroot"/boot

umount /mnt/boot
umount /mnt

losetup -d /dev/loop0
losetup -d /dev/loop1

dd bs=440 count=1 conv=notrunc \
    if=/usr/lib/syslinux/bios/mbr.bin of="$image_path"
